# sha256
sha_key: 'f2283984656d49d69e91c558476027ac'
java_distribution: openjdk
java_arch: linux-x64
java_major_version: jdk21
java_full_version: 21.0.2
java_package: '{{ java_distribution }}-{{ java_full_version }}_{{ java_arch }}_bin.tar.gz'
java_binaries_url: 'https://download.java.net/java/GA/jdk{{ java_full_version }}/{{ sha_key }}/13/GPL/{{ java_package }}'
java_tmp_folder: /opt/tmp
java_path: /opt
java_folder: '{{ java_path }}/java'
jmeter_binaries_url: https://archive.apache.org/dist/jmeter/binaries
#jmeter_version: '5.4.3'
jmeter_version: '5.6.3'
jmeter_checksum_url: 'https://archive.apache.org/dist/jmeter/binaries/{{ jmeter_package }}.sha512'
jmeter_checksum: >-
  {{ lookup('url', jmeter_checksum_url).split()[0] }}
jmeter_tmp_folder: /opt/tmp
jmeter_package: 'apache-jmeter-{{ jmeter_version }}.tgz'
jmeter_root_path: /opt
jmeter_report_path: '{{ jmeter_root_path }}/reports'
jmeter_path: '{{ jmeter_root_path }}/apache-jmeter-{{ jmeter_version }}'
jmeter_logs: '{{ jmeter_root_path }}/apache-jmeter-{{ jmeter_version }}/logs'
jmeter_userdata: '{{ jmeter_root_path }}/userdata'
jmeter_plugins: '{{ jmeter_root_path }}/plugins'
jmeter_heap_settings: "-Xms2G -Xmx2G -XX:MaxMetaspaceSize=256m"
jmeter_config_properties:
  - name: jmeter
    properties:
      - key: networkaddress.cache.negative.ttl
        value: 10
      - key: javax.net.debug
        value: ssl
      - key: server.rmi.ssl.disable
        value: true
      - key: server.rmi.localport
        value: 4000
      - key: client.rmi.localport
        value: 35750
      - key: jmeter.reportgenerator.apdex_satisfied_threshold
        value: 3000
      - key: jmeter.reportgenerator.apdex_tolerated_threshold
        value: 5000
win_java_arch: windows-x64
win_java_package: '{{ java_distribution }}-{{ java_full_version }}_{{ win_java_arch }}_bin.zip'
win_java_binaries_url: 'https://download.java.net/java/GA/jdk{{ java_full_version }}/{{ sha_key }}/13/GPL/{{ win_java_package }}'
win_java_tmp_folder: C:\tmp
win_java_path: 'C:\apps'
win_java_folder: '{{ win_java_path }}\java'
win_jmeter_tmp_folder: C:\tmp
win_jmeter_package: 'apache-jmeter-{{ jmeter_version }}.zip'
win_jmeter_binaries_url: 'https://archive.apache.org/dist/jmeter/binaries/{{ win_jmeter_package }}'
win_jmeter_root_path: C:\apps
win_jmeter_path: '{{ win_jmeter_root_path }}\jmeter'
win_jmeter_report_path: '{{ win_jmeter_path }}\reports'
win_jmeter_scripts_path: '{{ win_jmeter_path }}\scripts'
win_jmeter_results_path: '{{ win_jmeter_path }}\results'
win_jmeter_userdata: '{{ win_jmeter_path }}\userdata'
win_jmeter_workerdata: '{{ win_jmeter_path }}\workerdata'
win_jmeter_plugins: '{{ win_jmeter_path }}\plugins'
win_jmeter_logs: '{{ win_jmeter_path }}\apache-jmeter-{{ jmeter_version }}\logs'
win_jmeter_heap_settings: "-Xms4G -Xmx4G -XX:MaxMetaspaceSize=256m"
win_jmeter_config_properties_file: '{{ win_jmeter_path }}\apache-jmeter-{{ jmeter_version }}\bin\jmeter.properties'
win_jmeter_remote_hosts: "{{ groups['jmeterworker'] | join(',') }}"
win_jmeter_apdex_thresholds:
  - key: jmeter.reportgenerator.apdex_satisfied_threshold
    value: 3000
  - key: jmeter.reportgenerator.apdex_tolerated_threshold
    value: 5000
win_jmeter_rmi_properties:
  - key: server.rmi.ssl.disable
    value: true
  - key: server.rmi.localport
    value: 4000
  - key: client.rmi.localport
    value: 35750
win_jmeter_path_env:
  - '%SystemRoot%\system32'
  - '%SystemRoot%'
  - '%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\'
  - '%SYSTEMROOT%\System32\OpenSSH\'
  - C:\Program Files\Amazon\cfn-bootstrap\
  - C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps
  - '{{ win_jmeter_path }}\apache-jmeter-{{ jmeter_version }}\bin'
  - '{{ win_java_path }}\java\jdk-{{ java_full_version }}\bin'